FORMAT: 1A
HOST: https://api.flashy.app

# Flashy API Docs

Your account API key must be included in any request you send to Flashy API. You can send it in a few ways, choose the best one for you.

*   As a header in the request, the name of the header is "x-api-key" - Most recommended.
*   If you send a GET request you can pass the API key as query parameter "key=your_account_key".
*   If you send a request with body parameters you can include it as part of the request body as "key".
    

Before you can use our API, you must verify your Flashy account.

If you are using PHP we have a ready SDK wrapper - [PHP SDK](https://flashy.app/docs/php/).

* * *

*Before you can use our API, you must verify your Flashy account.*

## Account [/Account]

Read & manage your Flashy account information.

### Account [GET /account]

Get the current account.

+ Request (application/json)

+ Response 200 (application/json)

        {
                "success": true,
                "data": {
                        "id": 83,
                        "account": "r33piu",
                        "name": "My Account",
                        "country": null,
                        "website": "https://flashyapp.com",
                        "phone": "972526845430",
                        "credits": "24.0000",
                        "created_at": 1615565991,
                        "updated_at": 1631588013,
                        "timezone": "America/New_York",
                        "currency": "USD"
                }
        }




## Contacts [/Contacts]

Contacts are the foundation of the Flashy platform. You can create them based on any unique key that you prefer, with email being the default primary key.

We created a list of properties you can use to segment your contacts, and you can always create custom properties using our dashboard, read more about [Contact Properties](https://flashy.app/help/contact-management/utilizing-contact-properties/).

### Create [POST /contact]

Create or update contacts on Flashy by using the overwrite parameter.

Be sure to use the right Primary Key, our default is email address, but you can use any key you wish.

**You can add a contact to a specific list using the "lists" object, and the key is the List ID, and the value is true if the customer is marketing-eligible.**


+ Request (application/json)

    + Attributes
        + primary_key (required, string) - Name of the priamry key
        + overwrite (optional, boolean) - Update the contact if exists
        + contact (required, object) - Contact object
            + email (required, string) - Email
            + first_name (optional, string) - First name
            + last_name (optional, string) - Last name
            + birthday (optional, string) - Birthday

    + Body
        {
                "primary_key": "email",
                "overwrite": false,
                "contact": {
                        "email": "user1@name.com",
                        "first_name": "Rafael",
                        "last_name": "Mor",
                        "lists": {
                                "159": true,
                                "170": false
                        },
                        "birthday": 1631631569
                }
        }


+ Response 200 (application/json)

        {
                "success": true,
                "data": {
                        "email": "user1@name.com",
                        "first_name": "Rafael",
                        "last_name": "Mor",
                        "birthday": 1631631569,
                        "created_at": 1631631588,
                        "contact_id": "2291112565587e24668e171940cab7cc",
                        "lists": {}
                }
        }




### Update [PUT /contact/{contact_id}]

Update contact properties by the contact Primary Key.

Pay attention that the primary key of the contact needs to be part of the endpoint primary key to find a contact.

**Primary key can't be updated.**

+ Parameters
    + contact_id (required, string) - The contact identifier set on the endpoint URL
    + primary_key (optional, string) - The primary key to look the contacts based on, default is email

+ Request (application/json)

    + Attributes
        + contact (required, object) - The contact object with properties we want to update
            + last_name (optional, string) - The contact last name
            + source (optional, string) - The contact source
            + lists (optional, object) - Object of the lists and status of every list, key is the List ID and value is boolean

+ Response 200 (application/json)

        {
                "success": true,
                "data": {
                        "contact_id": "1a6711a68d0c381013ab72d3320ba4e5",
                        "email": "user1@name.com",
                        "birthday": 1631631569,
                        "created_at": 1632022656,
                        "phone": "",
                        "first_name": "Rafael",
                        "last_name": "Mor",
                        "source": "Google",
                        "lists": {}
                }
        }




### Get [GET /contact/{identifier}?primary_key={primary_key}]

Use your primary key to find a contact.

+ Parameters
    + identifier (required, string) - The contact identifier set on the endpoint URL
    + primary_key (optional, string) - The primary key to look the contacts based on, default is email

+ Request (application/json)


+ Response 200 (application/json)

        {
                "success": true,
                "data": {
                        "contact_id": "1a6711a68d0c381013ab72d3320ba4e5",
                        "email": "user1@name.com",
                        "birthday": 1631631569,
                        "created_at": 1632022656,
                        "phone": "",
                        "first_name": "Rafael",
                        "last_name": "Mor",
                        "lists": {}
                }
        }




### Example: Get By Contact ID [GET /contact/1a6711a68d0c381013ab72d3320ba4e5?primary_key=contact_id]

Use your primary key to find a contact.

+ Parameters
    + primary_key (optional, string) - The primary key to look the contacts based on, default is email

+ Request (application/json)


+ Response 200 (application/json)

        {
                "success": true,
                "data": {
                        "contact_id": "1a6711a68d0c381013ab72d3320ba4e5",
                        "email": "user1@name.com",
                        "birthday": 1631631569,
                        "created_at": 1632022656,
                        "phone": "",
                        "first_name": "Rafael",
                        "last_name": "Mor",
                        "lists": {}
                }
        }




### Example: Get By Email [GET /contact/user1@name.com?primary_key=email]

Use your primary key to find a contact.

+ Parameters
    + primary_key (optional, string) - The primary key to look the contacts based on, default is email

+ Request (application/json)


+ Response 200 (application/json)

        {
                "success": true,
                "data": {
                        "contact_id": "1a6711a68d0c381013ab72d3320ba4e5",
                        "email": "user1@name.com",
                        "birthday": 1631631569,
                        "created_at": 1632022656,
                        "phone": "",
                        "first_name": "Rafael",
                        "last_name": "Mor",
                        "lists": {}
                }
        }




### Block [POST /contact/{contact_id}/block?primary_key={primary_key}]

You can mark a contact as blocked whenever you don't want them to receive Flashy emails and SMS messages. The platform will then mark him as unsubscribed on all mailing lists he is a member of.

The contact can sign up again and the status will change to subscribed based on the list he signed up for.

+ Parameters
    + contact_id (required, string) - The contact identifier set on the endpoint URL
    + primary_key (optional, string) - The primary key to look the contacts based on, default is email

+ Request (application/json)




## Lists [/Lists]

Manage your newsletter lists.

### All Lists [GET /lists]

Get all the lists of the account.

**If you need to subscribe contact to a list, look on the Contact Create / Update.**

+ Request (application/json)

+ Response 200 (application/json)

        {
                "success": true,
                "data": [
                        {
                                "id": 4,
                                "title": "First List",
                                "updated_at": 1617091503
                        },
                        {
                                "id": 5,
                                "title": "Second List",
                                "updated_at": 1617091621
                        }
                ]
        }




## Messages [/Messages]

Flashy is an omnichannel platform that lets you send email, SMS and push notifications.

Utilize our API to communicate with your customers via the channel that you choose.

### Send Email [POST /messages/email]

Using our Drag & Drop editor, you can design and maintain your email templates, and you can pass the template ID in the API to send beautiful responsive email templates.

As an alternative to using one of your email templates, you can pass the HTML as part of the request.


+ Request (application/json)

    + Attributes
        + message (required, object) - Full Message
            + One Of
                + html (required, string) - Email Address
                + template (required, string) - Template
            + subject (required, string) - Subject
            + from (required, object) - Author object
                + name (required, string) - Name of the author
                + email (required, string) - Email of the author
            + to (required, object) - Receiver object
                + name (required, string) - Name of the receiver
                + email (required, string) - Email of the receiver
            + vars (optional, object) - Variables object of anything you want to add to the template
                + anything (optional, string) - Any key value items you want to add

    + Body
        {
                "message": {
                        "html": "<html><head><title>Email Page Title</title></head><body><h1>Hello World!</h1><p>Sent from Flashyapp.</p></body></html>",
                        "subject": "Anything",
                        "from": {
                                "name": "Flashy API Test",
                                "email": "dev@flashyapp.com"
                        },
                        "to": {
                                "name": "Test User",
                                "email": "hello@flashyapp.com"
                        },
                        "vars": {
                                "unique_hash": "somethinghere"
                        }
                }
        }


+ Response 200 (application/json)

        {
                "success": true,
                "data": null
        }




### Send SMS [POST /messages/sms]

SMS messages can be sent worldwide through Flashy platform. Make sure you include the country prefix on the phone number. As an example, in order to send SMS to a United Kingdom phone number, the number must include the 44 country code.

[List of county codes](https://en.wikipedia.org/wiki/List_of_country_calling_codes)

You must have credits on your account in order to send SMS messages.


+ Request (application/json)

    + Attributes

    + Body
        {
                "message": {
                        "from": "Flashyapp",
                        "to": "972526845430",
                        "message": "Hello World!",
                        "transactional": false
                }
        }


+ Response 200 (application/json)

        {
                "success": true,
                "data": null
        }




## Search [/Search]

Search contacts.

### Contacts [GET /search?type=contacts&query={query}]

Search contacts using a phone number or email address. If searching by phone, exclude the "+" sign and enter the number with the international prefix.

+ Parameters
    + type (required, string) - The default is "contacts"
    + query (required, string) - The email address or phone number of the contact you are looking for

+ Request (application/json)


+ Response 200 (application/json)

        {
                "success": true,
                "data": {
                        "results": [
                                {
                                        "contact_id": "ffbed8733ed83e70bc88910d6de71ef0",
                                        "email": "user@name.com",
                                        "phone": "972526845999",
                                        "created_at": 1631625209
                                }
                        ],
                        "total": 1
                }
        }




## Events [/Events]

The `Events` resource contains endpoints related to the tracking and management of user interactions within our marketing automation platform. Events are pivotal in triggering automations and collecting data about contact activities. These events can be generated both from online and offline interactions, enabling a comprehensive tracking system. Online events typically originate from digital interactions, while offline events are sourced from non-digital or physical world interactions.

### Event [POST /event]

Send events to keep track on your contacts activity and start automations based on them.

You can read more about all the event types we support here: [Events List](https://flashy.app/docs/tracking-events-api/).

There is always an option to use Custom Event but we suggest to use our pre-defined events if exists.

+ Request (application/json)

    + Body
        {
                "event": "ViewContent",
                "body": {
                        "email": "contact@company.com",
                        "content_ids": [
                                "38", "789"
                        ]
                }
        }


+ Response 200 (application/json)

        {
                "success": true,
                "data": null
        }




### Offline Event [POST /event/offline]

Send events from Offline sources, the main difference here is we have a fallback on the contact primary key, first we look by Email and if not found we look the contact by Phone, make sure to add both the primary key you have so we will have a better match.

This endpoint is from the Master plan and above.

**Make sure to use the Country Code if you include a phone number,** [List of Countries Code](https://en.wikipedia.org/wiki/List_of_country_calling_codes).

+ Request (application/json)

    + Body
        {
                "event": "Purchase",
                "body": {
                        "order_id": "159",
                        "value": 150,
                        "currnecy": "USD",
                        "phone": "972526845400",
                        "email": "contact@company.com",
                        "content_ids": [
                                "38", "789"
                        ],
                        "channel": "offline",
                        "branch": "San Francisco"
                }
        }


+ Response 200 (application/json)

        {
                "success": true,
                "data": null
        }




## Reports [/Reports]

### Email Campaigns [GET /reports/emails?from={from}&to={to}]

Retrieve detailed reports for all sent email campaigns within a specified date range. This endpoint provides comprehensive statistics and performance metrics for campaigns sent during the defined period.

+ Parameters
    + from (required, number) - The Unix timestamp after campaign is sent
    + to (required, number) - The Unix timestamp before campaign is sent

+ Request (application/json)


+ Response 200 (application/json)

        {
                "success": true,
                "data": [
                        {
                                "campaign_id": 24,
                                "campaign_name": "Any Campaign Title",
                                "subject_line": "The campaign subject line",
                                "sent_date": "2021-12-29",
                                "sent_time": "06:27:11",
                                "day_of_week": "Wednesday",
                                "total_recipients": 300,
                                "total_delivered": 300,
                                "delivery_rate": "100%",
                                "total_opens": 0,
                                "open_rate": "0%",
                                "unique_clicks": 0,
                                "total_clicks": 10,
                                "click_through_rate_ctr": "0%",
                                "purchases": 0,
                                "conversion_rate": "0%",
                                "revenue_generated": "$0.00",
                                "avg_purchase_value": "$0.00",
                                "revenue_per_message": "$0.00",
                                "total_bounces": 0,
                                "soft_bounces": 0,
                                "hard_bounces": 0,
                                "bounce_rate": "0%",
                                "unsubscribed": 0,
                                "unsubscribe_rate": "0%",
                                "total_spam": 0,
                                "spam_rate": "0%"
                        }
                ]
        }




### SMS Campaigns [GET /reports/sms?from={from}&to={to}]

Retrieve detailed reports for all sent SMS campaigns within a specified date range. This endpoint provides comprehensive statistics and performance metrics for campaigns sent during the defined period.

+ Parameters
    + from (required, number) - The Unix timestamp after campaign is sent
    + to (required, number) - The Unix timestamp before campaign is sent

+ Request (application/json)


+ Response 200 (application/json)

        {
                "success": true,
                "data": [
                        {
                                "campaign_id": 72,
                                "campaign_name": "Campaign Title",
                                "sent_date": "2022-05-30",
                                "sent_time": "09:10:32",
                                "day_of_week": "Monday",
                                "total_recipients": 100,
                                "total_delivered": 100,
                                "delivery_rate": "100%",
                                "unique_clicks": 1,
                                "total_clicks": 1,
                                "click_through_rate_ctr": "1.00%",
                                "purchases": 0,
                                "conversion_rate": "0%",
                                "revenue_generated": "$0.00",
                                "avg_purchase_value": "$0.00",
                                "revenue_per_message": "$0.00",
                                "failed_rate": "0%",
                                "unsubscribed": 0,
                                "unsubscribe_rate": "0%"
                        }
                ]
        }




### Automations [GET /reports/automations?from={from}&to={to}]

Retrieve detailed reports for all automations executed within a specified date range, with a maximum allowed timespan of 31 days. The data is broken down by automation and date, allowing you to access highly specific performance metrics and insights for each automation on a day-by-day basis.

+ Parameters
    + from (required, number) - Unix timestamp of starting the automation
    + to (required, number) - Unix timestamp of completeing the automation

+ Request (application/json)




## Webhooks [/Webhooks]

The `Webhooks` resource enables users to set up custom webhooks that are triggered by specific events on our platform. This feature allows users to receive real-time notifications to a specified URL when designated events occur. It enhances integration capabilities, allowing for automated reactions in external systems or applications in response to activities within our platform.

### Index [GET /webhooks]

Retrieve a list of all webhooks configured for a specific account. This endpoint provides an overview of active webhooks, including their URLs and the events they are set to listen to. It's useful for managing and reviewing webhook configurations.

+ Request (application/json)



### List [GET /webhooks/list]

Fetch a list of available events that webhooks can listen to. This endpoint helps users understand what events they can set webhooks for, such as 'contact_created', 'email_campaign_opened', etc. It's a key resource for planning and setting up new webhooks.

+ Request (application/json)



### Create [POST /webhook]

Allows users to create a new webhook. Users can specify the URL where notifications should be sent and select the events they want to monitor. This endpoint is essential for integrating real-time event monitoring into external systems.

+ Request (application/json)

    + Body
        {
        "endpoint": "https://mydomain.com/",
        "events": ["contact_created", "email_campaign_opened"]
}




### Update [PUT /webhook]

Update the settings of an existing webhook. This endpoint allows users to modify the list of events a webhook listens to or change its destination URL. It is crucial for maintaining and adjusting webhook configurations as user needs evolve.

+ Request (application/json)



### Delete [DELETE /webhook]

Permanently deletes a specified webhook and stops all its event notifications. This endpoint is used to clean up webhooks that are no longer needed, ensuring that the user's webhook configuration remains relevant and efficient.

+ Request (application/json)



